--CRIA UM LOGIN DE USUARIO
CREATE LOGIN maria WITH PASSWORD = '123';

--CRIA UM USUARIO DENTRo DE UM BANCO DE DADOS
CREATE USER maria FOR LOGIN maria;

--COMANDO DENY - BLOQUEIA O ACESSO
DENY INSERT, UPDATE, DELETE
TO maria;

--COMANDO REVOKE - REVERTE A PERMISSÂO DO USUÁRIO
REVOKE INSERT, UPDATE, DELETE
TO maria;